In [177]:
import numpy as np

In [178]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([1, -1, 0])
a, b

(array([1., 2., 3.]), array([ 1, -1,  0]))

In [179]:
a.dtype, b.dtype

(dtype('float64'), dtype('int32'))

In [180]:
a[0], b[1]

(1.0, -1)

In [181]:
print(a + b, a * b)
print(5 * b, b / 5)
print((a+b).dtype, (a*b).dtype, (5*b).dtype, (5.0*b).dtype)

[2. 1. 3.] [ 1. -2.  0.]
[ 5 -5  0] [ 0.2 -0.2  0. ]
float64 float64 int32 float64


In [182]:
print(np.dot(a, b))
print(np.matmul(a, b))
print(np.matmul(a, b.T))

-1.0
-1.0
-1.0


In [183]:
print(b, b.T)
print(b.shape)
print(b.T.shape)
print(b == b.T)

[ 1 -1  0] [ 1 -1  0]
(3,)
(3,)
[ True  True  True]


In [184]:
print(np.all(b == b))
print(a == b)
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html

True
[ True False False]


In [185]:
print(np.all(a == b))
print(np.any(a == b))

False
True


In [186]:
a[a == b]

array([1.])

In [187]:
b2 = np.array([b])
print(b2)
print(b2.shape)

[[ 1 -1  0]]
(1, 3)


In [188]:
print(b2.T)
print(b2.T.shape)

[[ 1]
 [-1]
 [ 0]]
(3, 1)


In [189]:
#np.matmul(b2, b2)

In [190]:
np.matmul(b2, b2.T)

array([[2]])

In [191]:
np.vstack((b, b, b))

array([[ 1, -1,  0],
       [ 1, -1,  0],
       [ 1, -1,  0]])

In [192]:
np.hstack((a.T, a.T, a.T))

array([1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [193]:
c = np.array([[1, 2], [3, 4]])
print(c, '\n')
print(c.T, '\n')

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]] 



In [194]:
e = np.eye(2)
print(e, '\n')
print(c * e, '\n')
print(np.matmul(c, e))

[[1. 0.]
 [0. 1.]] 

[[1. 0.]
 [0. 4.]] 

[[1. 2.]
 [3. 4.]]


In [195]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [196]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [197]:
np.arange(0, 1, 0.1), np.linspace(0, 1, 10)

(array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]))

In [198]:
r = np.arange(0, 11, 2)
r

array([ 0,  2,  4,  6,  8, 10])

In [199]:
m = np.outer(r, r + 1)
m

array([[  0,   0,   0,   0,   0,   0],
       [  2,   6,  10,  14,  18,  22],
       [  4,  12,  20,  28,  36,  44],
       [  6,  18,  30,  42,  54,  66],
       [  8,  24,  40,  56,  72,  88],
       [ 10,  30,  50,  70,  90, 110]])

In [200]:
m[1,0]

2

In [201]:
m[0], m[0,:], m[:,0]

(array([0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0]),
 array([ 0,  2,  4,  6,  8, 10]))

In [202]:
m[1:,1:-1]

array([[ 6, 10, 14, 18],
       [12, 20, 28, 36],
       [18, 30, 42, 54],
       [24, 40, 56, 72],
       [30, 50, 70, 90]])

In [203]:
m[1::2,:]

array([[  2,   6,  10,  14,  18,  22],
       [  6,  18,  30,  42,  54,  66],
       [ 10,  30,  50,  70,  90, 110]])

In [204]:
m[:,::-1]

array([[  0,   0,   0,   0,   0,   0],
       [ 22,  18,  14,  10,   6,   2],
       [ 44,  36,  28,  20,  12,   4],
       [ 66,  54,  42,  30,  18,   6],
       [ 88,  72,  56,  40,  24,   8],
       [110,  90,  70,  50,  30,  10]])

In [205]:
#m > 5 and m < 15

In [206]:
x = np.logical_and(m > 5, m < 15)
x

array([[False, False, False, False, False, False],
       [False,  True,  True,  True, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [ True, False, False, False, False, False]])

In [207]:
m[x]

array([ 6, 10, 14, 12,  6,  8, 10])

In [208]:
m * x

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  6, 10, 14,  0,  0],
       [ 0, 12,  0,  0,  0,  0],
       [ 6,  0,  0,  0,  0,  0],
       [ 8,  0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0,  0]])

In [209]:
m * ~x

array([[  0,   0,   0,   0,   0,   0],
       [  2,   0,   0,   0,  18,  22],
       [  4,   0,  20,  28,  36,  44],
       [  0,  18,  30,  42,  54,  66],
       [  0,  24,  40,  56,  72,  88],
       [  0,  30,  50,  70,  90, 110]])

In [210]:
z = np.exp([1, 2, 3])
np.e

2.718281828459045

In [211]:
np.log(z)

array([1., 2., 3.])

In [212]:
10**a, np.log10(10**a)

(array([  10.,  100., 1000.]), array([1., 2., 3.]))

In [213]:
np.pi, np.e

(3.141592653589793, 2.718281828459045)

In [214]:
y = [0, np.pi/6, np.pi/2]
np.sin(y)

array([0. , 0.5, 1. ])

In [215]:
X, Y = np.array([1, 2, 3]), np.array([110, 210, 310])
result = np.polyfit(X, Y, 1)
result

array([100.,  10.])

In [216]:
result[0] * X + result[1]

array([110., 210., 310.])